Sistema_analisis_estadistico/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
import os


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('file_handler.urls')),
    path('data_cleaning/', include('data_cleaning.urls')),
    path('data_transformation/', include('data_transformation.urls')),
    path('data_analysis/', include ('data_analysis.urls')),
    path('report/', include('report.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static('/temp_files/', document_root=os.path.join(settings.BASE_DIR, 'temp_files'))

data_transformation/urls.py
from . import views
from django.urls import path


app_name = 'data_transformation'

urlpatterns = [
    path('transformation/<str:file_name>', views.transformation, name='transformation'),
    path('standardization/<str:file_name>', views.standardization, name='standardization')
]

report/urls.py
from . import views
from django.urls import path

app_name = 'report'

urlpatterns = [
    path('exportar_reporte/', views.exportar_reporte, name='exportar_reporte'),

    path('reporte_distribucion_frecuencias/<str:file_name>', views.reporte_distribucion_frecuencias, name='reporte_distribucion_frecuencias'),
    path('reporte_tendencia_central/<str:file_name>', views.reporte_tendencia_central, name='reporte_tendencia_central'),
    path('reporte_variabilidad/<str:file_name>', views.reporte_variabilidad, name='reporte_variabilidad'),    


    path('reporte_regresion_linear/<str:file_name>', views.reporte_regresion_linear, name='reporte_regresion_linear'),
    path('reporte_regresion_logistica/<str:file_name>', views.reporte_regresion_logistica, name='reporte_regresion_logistica'),  
    path('reporte_correlacion_pearson/<str:file_name>', views.reporte_correlacion_pearson, name='reporte_correlacion_pearson'),
    path('reporte_correlacion_spearman/<str:file_name>', views.reporte_correlacion_spearman, name='reporte_correlacion_spearman'),  
    path('reporte_kmeans_clustering/<str:file_name>', views.reporte_kmeans_clustering, name='reporte_kmeans_clustering'),  
    path('reporte_arbol_decision_clasificacion/<str:file_name>', views.reporte_arbol_decision_clasificacion, name='reporte_arbol_decision_clasificacion'),


    path('reporte_intervalo_confianza/<str:file_name>', views.reporte_intervalo_confianza, name='reporte_intervalo_confianza'),  
    path('reporte_prueba_hipotesis/<str:file_name>', views.reporte_prueba_hipotesis, name='reporte_prueba_hipotesis'),
    path('reporte_perceptron/<str:file_name>', views.reporte_perceptron, name='reporte_perceptron'),    

]

data_transformation/models.py
from django.db import models

# Create your models here.

data_transformation/views.py
from django.shortcuts import render
from django.shortcuts import redirect, render
from .utils import standardization_utils, transformation_utils
from .utils.views_utils import guardar_resultado_en_sesion, preparar_datos_para_get
from utils.csv_utils import gestionar_version_archivo, leer_csv_o_error, guardar_csv

# Vistas de transformación de datos y estandarización.
# Se encargan de recibir los datos del usuario, procesarlos y enviarlos a la vista de revisión de datos.
# Se incluyen las vistas: transformation y standardization

def transformation(request, file_name):
    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')


    df_html, columnas = preparar_datos_para_get(df, include_dtypes=['category'])

    unique_values = {col: df[col].dropna().unique().tolist() for col in columnas}
    # Se cre un nuevo diccionario para el contexto que contenga tanto las columnas como sus valores únicos
    column_info = {col: {'values': unique_values[col]} for col in columnas if col in unique_values}
    orders = {}


    if request.method == 'POST':
        tipo = request.POST.get('tipo', '')
        columnas_a_manipular = request.POST.getlist('columnas_a_manipular')

        if not columnas_a_manipular:
            error_message = "Debe seleccionar al menos una columna."
            return render(request, 'data_transformation/transformation.html', {
                'file_name': file_name,
                'dataframe': df_html,
                'columnas': columnas,
                'column_info': column_info,
                'orders': orders,
                'error_message': error_message
            })

        new_file_name, new_file_path = gestionar_version_archivo(request, file_name)
        
        # Recolección de los órdenes para el codificador ordinal
        orders = {}
        for columna in columnas_a_manipular:
            if tipo == 'ordinalencoder':
                order_key = f'ordinal_order_{columna}'
                orders[columna] = request.POST.get(order_key, '').split(',')

        df_procesado, resultado = transformation_utils.transformationStand(df, tipo, columnas_a_manipular, orders=orders)

        guardar_resultado_en_sesion(request, resultado)
        guardar_csv(df_procesado, new_file_path)
        return redirect('file_handler:revisar_csv', file_name=new_file_name)

    return render(request, 'data_transformation/transformation.html', {
        'file_name': file_name,
        'columnas': columnas,
        'column_info': column_info,
        'orders': orders,
        'dataframe': df_html
    })

def standardization(request, file_name):

    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')

    # Preparación para el método GET
    df_html, columnas = preparar_datos_para_get(df, include_dtypes=['number'])


    # Manejo de POST
    if request.method == 'POST':
        tipo = request.POST.get('tipo','')
        columnas_a_manipular = request.POST.getlist('columnas_a_manipular')
        
        if not columnas_a_manipular:
            error_message = "Debe seleccionar al menos una columna."
            return render(request, 'data_transformation/standardization.html', {
                'file_name': file_name,
                'dataframe': df_html,
                'columnas': columnas,
                'error_message': error_message
            })
        
        new_file_name, new_file_path = gestionar_version_archivo(request, file_name)

        df_procesado, resultado = standardization_utils.standardization(df, tipo, columnas_a_manipular)

        guardar_resultado_en_sesion(request, resultado)
        guardar_csv(df_procesado, new_file_path)
        return redirect('file_handler:revisar_csv', file_name=new_file_name)


    return render(request, 'data_transformation/standardization.html', {
        'file_name': file_name,
        'columnas': columnas, 
        'dataframe': df_html
    })

data_transformation/templates/data_transformation/plantilla_opciones.html
{% extends "layouts/base.html" %}

{% block title %}Transformación{% endblock %}

{% block content %}
<div class="d-flex flex-column gap-2">
    <div class="bg-white rounded shadow p-4 mt-4 flex-shrink-1">
        {% block formulario%}

        {% if error_message %}
        <div class="alert alert-danger mb-4" role="alert">
            {{ error_message }}
        </div>
        {% endif %}
        
        <div>
            <button type="submit" class="btn btn-primary">Aplicar transformación</button>
        </div>

        {% endblock %}	
    </div>

    <div class="flex-fill">
        {% include "file_handler/_scrollable_table.html" %}
    </div>

</div>
{% endblock %}

data_transformation/templates/data_transformation/standardization.html
{% extends "data_transformation/plantilla_opciones.html" %}

{% block formulario %}

<form action="{% url 'data_transformation:standardization' file_name=file_name %}" method="post">
    {% csrf_token %}
    <div class="d-flex align-items-center mb-4 justify-content-between">
        <h5 class="mb-0 me-4">Escalado y estandarización de datos</h5>
        <!-- Botón para abrir el modal -->
        <button type="button" class="btn btn-outline-info p-1" data-bs-toggle="modal" data-bs-target="#modalInstrucciones">
            <i class="bi bi-book"></i> Ayuda
        </button>
    </div>

    <div class="d-flex gap-4 justify-content-start flex-wrap mt-2 mb-4">

        <div>
            <p>Seleccione el tipo de escalado:</p>
            <select class="form-select" id="tipo" name="tipo">
                <option value="minmax">Escalado MinMax</option>
                <option value="maxabs">Escalado MaxAbs</option>
                <option value="estandar">Escalado Estándar</option>
            </select>
        </div>

        <div style="width: 100%">
            <p>Seleccione las columnas que desea modificar:</p>
            <div class="form-check mb-2">
                <!-- Casilla para seleccionar o deseleccionar todo -->
                <input class="form-check-input" type="checkbox" id="seleccionar_todo">
                <label class="form-check-label mb-2" for="seleccionar_todo" style="font-weight: bold;">
                    Seleccionar todo
                </label>
            </div>
            {% if columnas %}
                <!-- Distribución de columnas -->
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-6 g-0">
                    {% for columna in columnas %}
                    <div class="col" style="overflow: hidden">
                        <div class="form-check mb-2">
                            <input class="form-check-input column-checkbox" type="checkbox" name="columnas_a_manipular" value="{{ columna }}" id="check_{{ columna }}">
                            <label class="form-check-label text-truncate" for="check_{{ columna }}" title="{{ columna }}" style="max-width: 90%; cursor: pointer;">
                                {{ columna }}
                            </label>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                <small class="text-info">
                    <i class="bi bi-info-circle-fill"></i> No hay columnas disponibles para modificar.
                </small>
            {% endif %}
        </div>
        

    </div>

    {{ block.super }}
</form>

<!-- seleccionar todo -->
<script>
    document.getElementById('seleccionar_todo').addEventListener('change', function() {
        var checkboxes = document.querySelectorAll('[name="columnas_a_manipular"]');
        checkboxes.forEach(chk => {
            chk.checked = this.checked;
        });
    });
</script>

<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
        $('#modalInstrucciones').on('hidden.bs.modal', function () {
        });
    });
</script>

<!-- Modal de Instrucciones de Uso -->
<div class="modal fade" id="modalInstrucciones" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Instrucciones de uso</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>Escalado y Estandarización de Datos</h5>
                <p>El normalizar los valores de las variables, asegurando que todas las características contribuyan de manera equitativa al análisis o modelado.</p>

                <hr>
                <h5>Tipos de Escalado</h5>
                <ol>
                    <li><strong>Escalado MinMax:</strong> Este método transforma los valores de las variables a un rango específico, generalmente entre 0 y 1.</li>
                    <li><strong>Escalado MaxAbs:</strong> Este método escala los valores a un rango de -1 a 1, dividiendo cada valor por el valor absoluto máximo de la variable.</li>
                    <li><strong>Escalado Estándar:</strong> Este método transforma los valores para que tengan una media de 0 y una desviación estándar de 1.</li>
                </ol>

                <hr>
                <h5>Pasos a Seguir</h5>
                <ol>
                    <li><strong>Seleccione el Tipo de Escalado:</strong> Elija el método de escalado que mejor se adapte a sus datos y necesidades específicas.</li>
                    <li><strong>Seleccione las Columnas que Desea Modificar:</strong> Decida qué columnas del dataset desea escalar o estandarizar. Puede seleccionar todas las columnas o elegir columnas específicas.</li>
                </ol>

                <hr>
                <h6>Ejemplo</h6>
                <div class="text-center">
                    <pre>| Valor 1 | Valor 2 |
| --- | --- |
| 10  | 200 |
| 15  | 300 |
| 20  | 250 |
| 25  | 400 |
| 30  | 350 |</pre>
                </div>

                <hr>
                <h6>Tipo de Escalado: Escalado MinMax</h6>
                <h6>Resultados</h6>
                <div class="text-center">
                    <pre>Aplicando el Escalado MinMax, los valores se transforman al rango [0, 1]:

| Valor 1 | Valor 2 |
| --- | --- |
| 0.0 | 0.0 |
| 0.25 | 0.5 |
| 0.5 | 0.25 |
| 0.75 | 1.0 |
| 1.0 | 0.75 |</pre>
                </div>
                <p>En este ejemplo, los valores de ambas columnas se han escalado al rango [0, 1] utilizando el método de Escalado MinMax.</p>
            </div>
        </div>
    </div>
</div>


{% endblock %}

data_transformation/templates/data_transformation/transformation.html
{% extends "data_transformation/plantilla_opciones.html" %}

{% block formulario %}

<form action="{% url 'data_transformation:transformation' file_name=file_name %}" method="post">
    {% csrf_token %}
    <div class="d-flex align-items-center mb-4 justify-content-between">
        <h5 class="mb-0 me-4">Transformación de variables categorías</h5>
        <!-- Botón para abrir el modal -->
        <button type="button" class="btn btn-outline-info p-1" data-bs-toggle="modal" data-bs-target="#modalInstrucciones">
            <i class="bi bi-book"></i> Ayuda
        </button>
    </div>

    <div class="d-flex gap-4 justify-content-start flex-wrap mt-2 mb-4">
        <div>
            <p>Seleccione el tipo de transformación:</p>
            <select class="form-select" id="tipo" name="tipo">
                <option value="labelencoder">Codificador de etiquetas</option>
                <option value="one_hot">One-hot</option>
                <option value="ordinalencoder">Codificador ordinal</option>
            </select>
        </div>
        
        <div style="width: 100%">
            <p>Seleccione las columnas que desea transformar:</p>
            <div class="form-check mb-2">
                <!-- Casilla para seleccionar o deseleccionar todo -->
                <input class="form-check-input" type="checkbox" id="seleccionar_todo">
                <label class="form-check-label mb-2" for="seleccionar_todo" style="font-weight: bold;">
                    Seleccionar todo
                </label>
            </div>
            <!-- Distribución de columna -->
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-6 g-0">
                {% for columna in columnas %}
                <div class="col" style="overflow: hidden">
                    <div class="form-check mb-2">
                        <input class="form-check-input column-checkbox" type="checkbox" name="columnas_a_manipular" value="{{ columna }}" id="check_{{ columna }}">
                        <label class="form-check-label text-truncate" for="check_{{ columna }}" title="{{ columna }}" style="max-width: 90%; cursor: pointer;">
                            {{ columna }}
                        </label>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% if not columnas %}
                <small class="text-info">
                    <i class="bi bi-info-circle-fill"></i> No hay columnas disponibles para transformar.
                </small>
            {% endif %}
        </div>
        

        <div id="ordinal-options" class="mb-4" style="display: none; width: 100%">
            <div style="width: 100%">
                <p>Defina la jerarquía de las columnas seleccionadas:</p>
                <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-5" style="width: 100%">
                    {% for columna, info in column_info.items %}
                        <div id="ordinal_{{ columna }}" class="col" style="display: none;">
                            <div>
                                <div class="mb-3">
                                    <h6 class="card-title">{{ columna }}</h6>
                                    <div class="list-group list-group-flush" data-id="ordinal_{{ columna }}">
                                        {% for value in info.values %}
                                            <div class="list-group-item border rounded d-flex mb-2" data-id="{{ value }}">
                                                <i class="bi bi-grip-vertical"></i>
                                                {{ value }}
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <input type="hidden" name="ordinal_order_{{ columna }}" value="{{ info.values|join:',' }}">
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>    
            </div>
        </div>
        
    
        
    </div>

    {{ block.super }}
</form>

<!-- seleccionar todo -->
<script>
    document.getElementById('seleccionar_todo').addEventListener('change', function() {
        var checkboxes = document.querySelectorAll('[name="columnas_a_manipular"]');
        checkboxes.forEach(chk => {
            chk.checked = this.checked;
        });
    });
</script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.14.0/Sortable.min.js"></script>
<script>
    // Función para actualizar la visibilidad de las listas basadas en la opción seleccionada y las columnas marcadas
    function updateVisibility() {
        var selectedType = document.getElementById('tipo').value;
        var showOrdinal = selectedType === 'ordinalencoder';
        var ordinalOptions = document.getElementById('ordinal-options');
        ordinalOptions.style.display = showOrdinal ? 'flex' : 'none';

        document.querySelectorAll('.column-checkbox').forEach(checkbox => {
            var columnDiv = document.getElementById('ordinal_' + checkbox.value);
            if (checkbox.checked && showOrdinal) {
                columnDiv.style.display = 'block';
            } else {
                columnDiv.style.display = 'none';
            }
        });
    }

    // Evento para cuando cambia el tipo de transformación
    document.getElementById('tipo').addEventListener('change', function() {
        updateVisibility();
    });

    // Eventos para cuando se seleccionan las columnas
    document.querySelectorAll('.column-checkbox').forEach(checkbox => {
        checkbox.addEventListener('change', function() {
            updateVisibility();
        });
    });
</script>

<script>
    document.getElementById('seleccionar_todo').addEventListener('change', function() {
        var checkboxes = document.querySelectorAll('[name="columnas_a_manipular"]');
        var isChecked = this.checked;  // Guarda el estado del checkbox "Seleccionar todo"
        checkboxes.forEach(chk => {
            chk.checked = isChecked;
        });
        updateVisibility(); // Llama a la función para actualizar la visibilidad después de cambiar los estados de los checkboxes
    });

    document.addEventListener('DOMContentLoaded', function() {
        updateVisibility();  // Asegura que la visibilidad y los valores iniciales sean correctos al cargar
    });
</script>

<script>
    // Inicialización de Sortable para las listas de ordenación
    document.querySelectorAll('.list-group').forEach(function(el) {
        new Sortable(el, {
            animation: 150,
            ghostClass: 'blue-background-class',
            onUpdate: function(evt) {
                var order = Array.from(evt.from.children).filter(item => item.getAttribute('data-id') !== null).map(item => item.getAttribute('data-id').trim());
                var containerId = evt.from.getAttribute('data-id'); // Asegurarse de que se está obteniendo el atributo del contenedor correcto
                if (!containerId) {
                    console.error("Error: El contenedor no tiene ID.");
                    return;
                }
                var inputName = 'ordinal_order_' + containerId.replace('ordinal_', '');
                var inputElement = document.querySelector('input[name="' + inputName + '"]');
                inputElement.value = order.join(',');
            }
        });
    });
</script>

<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
        $('#modalInstrucciones').on('hidden.bs.modal', function () {
        });
    });
</script>


<!-- Modal de Instrucciones de Uso -->
<div class="modal fade" id="modalInstrucciones" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Instrucciones de uso</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>Transformación de Variables Categóricas</h5>
                <p>La transformación de variables categóricas implica convertir texto en números. Dependiendo del tipo de transformación que se elija. Puede ser un número que represente la cantidad de ítems que contenga la columna, o se puede crear una matriz donde se muestre un 1 donde esté presente el elemento y un 0 donde no lo esté.</p>

                <hr>
                <h5>Tipos de Transformación</h5>
                <ol>
                    <li><strong>Codificador de Etiquetas:</strong> Esta técnica asigna un número entero único a cada categoría presente en la columna.</li>
                    <li><strong>One-Hot Encoding:</strong> Esta técnica crea una nueva columna binaria para cada categoría presente en la columna original. Cada columna binaria indica la presencia o ausencia de esa categoría para cada fila.</li>
                    <li><strong>Codificación Ordinal:</strong> Esta técnica es similar al codificador de etiquetas con la diferencia que se pueden asignar los pesos de las etiquetas.</li>
                </ol>

                <hr>
                <h5>Pasos a Seguir</h5>
                <ol>
                    <li><strong>Seleccione el Tipo de Transformación:</strong> Elija el método de transformación que mejor se adapte a sus datos y necesidades específicas.</li>
                    <li><strong>Seleccione las Columnas que Desea Transformar:</strong> Decida qué columnas del dataset desea transformar de acuerdo con el tipo de transformación seleccionado.</li>
                </ol>

                <hr>
                <h6>Ejemplo</h6>
                <div class="text-center">
                    <pre>Tabla ejemplo
Categoría
---
A
---
B
---
A
---
C
---
B
---
A
---
C
---</pre>
                </div>

                <hr>
                <h6>Aplicación del método</h6>
                <div class="text-center">
                    <pre>Categoría
---
1
---
2
---
1
---
3
---
2
---
1
---
3
---</pre>
                </div>

                <hr>
                <h6>Transformación One-Hot:</h6>
                <div class="text-center">
                    <pre>| Categoría_A | Categoría_B | Categoría_C |
| --- | --- | --- |
| 1 | 0 | 0 |
| 0 | 1 | 0 |
| 1 | 0 | 0 |
| 0 | 0 | 1 |
| 0 | 1 | 0 |
| 1 | 0 | 0 |
| 0 | 0 | 1 |</pre>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}