Sistema_analisis_estadistico/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
import os


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('file_handler.urls')),
    path('data_cleaning/', include('data_cleaning.urls')),
    path('data_transformation/', include('data_transformation.urls')),
    path('data_analysis/', include ('data_analysis.urls')),
    path('report/', include('report.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static('/temp_files/', document_root=os.path.join(settings.BASE_DIR, 'temp_files'))

data_analysis/urls.py
from . import views
from django.urls import path

app_name = 'data_analysis'

# URLs para las vistas de análisis de datos

urlpatterns = [
   path('distribucion_frecuencias/<str:file_name>', views.distribucion_frecuencias, name='distribucion_frecuencias'),
   path('tendencia_central/<str:file_name>', views.tendencia_central, name='tendencia_central'),
   path('variabilidad/<str:file_name>', views.variabilidad, name='variabilidad'),

   path('regresion_lineal/<str:file_name>', views.regresion_lineal, name='regresion_lineal'),
   path('regresion_logistica/<str:file_name>', views.regresion_logistica, name='regresion_logistica'),
   path('correlacion_pearson/<str:file_name>', views.correlacion_pearson, name='correlacion_pearson'),
   path('correlacion_spearman/<str:file_name>', views.correlacion_spearman, name='correlacion_spearman'),
   path('kmeans_clustering/<str:file_name>', views.kmeans_clustering, name='kmeans_clustering'),
   path('arbol_decision_clasificacion/<str:file_name>', views.arbol_decision_clasificacion, name='arbol_decision_clasificacion'),

   path('intervalo/<str:file_name>', views.intervalo, name='intervalo'),
   path('prueba_hipotesis/<str:file_name>', views.prueba_hipotesis, name='prueba_hipotesis'),
   path('perceptron/<str:file_name>', views.perceptron, name='perceptron'),


]

report/urls.py
from . import views
from django.urls import path

app_name = 'report'

urlpatterns = [
    path('exportar_reporte/', views.exportar_reporte, name='exportar_reporte'),

    path('reporte_distribucion_frecuencias/<str:file_name>', views.reporte_distribucion_frecuencias, name='reporte_distribucion_frecuencias'),
    path('reporte_tendencia_central/<str:file_name>', views.reporte_tendencia_central, name='reporte_tendencia_central'),
    path('reporte_variabilidad/<str:file_name>', views.reporte_variabilidad, name='reporte_variabilidad'),    


    path('reporte_regresion_linear/<str:file_name>', views.reporte_regresion_linear, name='reporte_regresion_linear'),
    path('reporte_regresion_logistica/<str:file_name>', views.reporte_regresion_logistica, name='reporte_regresion_logistica'),  
    path('reporte_correlacion_pearson/<str:file_name>', views.reporte_correlacion_pearson, name='reporte_correlacion_pearson'),
    path('reporte_correlacion_spearman/<str:file_name>', views.reporte_correlacion_spearman, name='reporte_correlacion_spearman'),  
    path('reporte_kmeans_clustering/<str:file_name>', views.reporte_kmeans_clustering, name='reporte_kmeans_clustering'),  
    path('reporte_arbol_decision_clasificacion/<str:file_name>', views.reporte_arbol_decision_clasificacion, name='reporte_arbol_decision_clasificacion'),


    path('reporte_intervalo_confianza/<str:file_name>', views.reporte_intervalo_confianza, name='reporte_intervalo_confianza'),  
    path('reporte_prueba_hipotesis/<str:file_name>', views.reporte_prueba_hipotesis, name='reporte_prueba_hipotesis'),
    path('reporte_perceptron/<str:file_name>', views.reporte_perceptron, name='reporte_perceptron'),    

]

data_analysis/models.py
from django.db import models

# Create your models here.

data_analysis/views.py
import json
from django.shortcuts import render
from http.client import HTTPResponse
from django.shortcuts import redirect
import pandas as pd
from .utils.data_analysis_utils import guardar_resultado_en_sesion, preparar_datos_para_get
from utils.csv_utils import gestionar_version_archivo, leer_csv_o_error, guardar_csv
from utils.tablas_utils import crear_inicio_tabla
import numpy as np
import re 
from .utils import inferencial_utils
from .utils import correlacion_utils
from .utils import machine_learning_utils
from .utils import descriptiva_utils

from django.shortcuts import redirect

# Vistas de análisis de datos que son la conexión entre las plantillas y las funciones de utilidad.
# Aquí están todas las vistas dedicadas al analisis de datos.
# Se incluyen las funciones: distribucion_frecuencias, tendencia_central, variabilidad, regresion_lineal, regresion_logistica, correlacion_pearson, correlacion_spearman, kmeans_clustering, arbol_decision_clasificacion, intervalo y prueba_hipotesis.

def distribucion_frecuencias(request, file_name):
    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')

    # Obtener nombres de columnas categóricas
    columnas_categoricas = df.select_dtypes(include=['category']).columns.tolist()

    # Preparación para el método GET
    df_html, columnas = preparar_datos_para_get(df, include_dtypes=['category'])

    # Variables para el mensaje de error
    error_message = None

    # Obtener las primeras 10 filas para las columnas seleccionadas
    columnas_a_manipular = request.session.get('columnas_a_manipular', [])
    primeras_filas = df[columnas_a_manipular].head(10).to_dict(orient='list') if columnas_a_manipular else {}

    # Manejo de POST
    if request.method == 'POST':
        columnas_a_manipular = request.POST.getlist('columnas_a_manipular')

        if not columnas_a_manipular:
            error_message = "No se especificaron columnas para el análisis."
        else:
            # Calcular distribución de frecuencias utilizando la función en utils.py
            df, reporte_data, resultado = descriptiva_utils.calcular_distribucion_frecuencias(df, columnas_a_manipular)
            if resultado['Errores']:
                error_message = ', '.join(resultado['Errores'])
            else:
                # Guardar los resultados en la sesión para su posterior uso
                request.session['reporte_data'] = json.dumps(reporte_data)

                # Redirigir a la página del informe si no hay errores
                return redirect('report:reporte_distribucion_frecuencias', file_name=file_name)

    # Pasar las columnas al contexto del template incluso si hay un mensaje de error
    return render(request, 'data_analysis/distribucion_frecuencias.html', {
        'file_name': file_name,
        'columnas': columnas,
        'columnas_categoricas': columnas_categoricas,
        'dataframe': df_html,
        'error_message': error_message,
        "columna_seleccionada": columnas_a_manipular
    })

def tendencia_central(request, file_name):
    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')

    # Obtener nombres de columnas numéricas
    columnas_numericas = df.select_dtypes(include=['number']).columns.tolist()

    # Preparación para el método GET
    df_html, columnas = preparar_datos_para_get(df, include_dtypes=['number'])

    # Variables para el mensaje de error
    error_message = None

    # Obtener las primeras 10 filas para las columnas seleccionadas
    columnas_a_manipular = request.session.get('columnas_a_manipular', [])
    primeras_filas = df[columnas_a_manipular].head(10).to_dict(orient='list') if columnas_a_manipular else {}

    # Manejo de POST
    if request.method == 'POST':
        columnas_a_manipular = request.POST.getlist('columnas_a_manipular')

        if not columnas_a_manipular:
            error_message = "No se especificaron columnas para el análisis."
        else:
            # Calcular medidas de tendencia central utilizando la función en utils.py
            df, reporte_data, resultado = descriptiva_utils.calcular_tendencia_central(df, columnas_a_manipular)
            if resultado['Errores']:
                error_message = ', '.join(resultado['Errores'])
            else:
                # Guardar los resultados en la sesión para su posterior uso
                request.session['reporte_data'] = json.dumps(reporte_data)

                # Redirigir a la página del informe si no hay errores
                return redirect('report:reporte_tendencia_central', file_name=file_name)

    # Pasar las columnas al contexto del template incluso si hay un mensaje de error
    return render(request, 'data_analysis/tendencia_central.html', {
        'file_name': file_name,
        'columnas': columnas,
        'columnas_numericas': columnas_numericas,
        'dataframe': df_html,
        'error_message': error_message,
        "columna_seleccionada": columnas_a_manipular
    })

def variabilidad(request, file_name):
    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')

    # Obtener nombres de columnas numéricas
    columnas_numericas = df.select_dtypes(include=['number']).columns.tolist()

    # Preparación para el método GET
    df_html, columnas = preparar_datos_para_get(df, include_dtypes=['number'])

    # Variables para el mensaje de error
    error_message = None

    # Obtener las primeras 10 filas para las columnas seleccionadas
    columnas_a_manipular = request.session.get('columnas_a_manipular', [])
    primeras_filas = df[columnas_a_manipular].head(10).to_dict(orient='list') if columnas_a_manipular else {}

    # Manejo de POST
    if request.method == 'POST':
        columnas_a_manipular = request.POST.getlist('columnas_a_manipular')

        if not columnas_a_manipular:
            error_message = "No se especificaron columnas para el análisis."
        else:
            # Calcular medidas de variabilidad utilizando la función en utils.py
            df, reporte_data, resultado = descriptiva_utils.calcular_variabilidad(df, columnas_a_manipular)
            if resultado['Errores']:
                error_message = ', '.join(resultado['Errores'])
            else:
                # Guardar los resultados en la sesión para su posterior uso
                request.session['reporte_data'] = json.dumps(reporte_data)

                # Redirigir a la página del informe si no hay errores
                return redirect('report:reporte_variabilidad', file_name=file_name)

    #Pasar las columnas al contexto del template incluso si hay un mensaje de error
    return render(request, 'data_analysis/variabilidad.html', {
        'file_name': file_name,
        'columnas': columnas,
        'columnas_numericas': columnas_numericas,
        'dataframe': df_html,
        'error_message': error_message,
        "columna_seleccionada": columnas_a_manipular
    })


def regresion_lineal(request, file_name):
    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')
    
    # Preparación para el método GET
    df_html, columnas = preparar_datos_para_get(df, include_dtypes=['number'])

    #Manejo de POST
    if request.method == 'POST':
        variable_dependiente = request.POST.get('variable_dependiente')
        variables_independientes = request.POST.getlist('variables_independientes')
        
        # Verificar si se han seleccionado variables
        if not variable_dependiente or not variables_independientes:
            error_message = "Debe seleccionar al menos una variable dependiente y una variable independiente."
            return render(request, 'data_analysis/regresion_lineal.html', {
                'file_name': file_name,
                'columnas': columnas,
                'dataframe': df_html,
                'error_message': error_message
            })

        new_file_name, new_file_path = gestionar_version_archivo(request, file_name)
        df_procesado, reporte_data, resultado = inferencial_utils.regresion_linear(df, variable_dependiente, variables_independientes)
        
        if(resultado['Errores']):
            guardar_resultado_en_sesion(request, resultado)
            return redirect('file_handler:revisar_csv', file_name=new_file_name)

        request.session['reporte_data'] = json.dumps(reporte_data)

        guardar_csv(df_procesado, new_file_path)
        return redirect('report:reporte_regresion_linear', file_name=new_file_name)
    
    return render(request, 'data_analysis/regresion_lineal.html', {
        'file_name': file_name,
        'columnas': columnas,
        'dataframe': df_html
    })

def regresion_logistica(request, file_name):
    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')
    
    # Preparación para el método GET
    df_html, columnas = preparar_datos_para_get(df, include_dtypes=['number'])
    
    columnas_binarias = []
    columnas_numericas = df.select_dtypes(include=['float64', 'int', 'bool']).columns.tolist()

    for columna in df.columns:
        # Obtener valores únicos de la columna excluyendo NaN
        valores_unicos = pd.unique(df[columna].dropna())

        # Convertir valores únicos a strings para verificar si son numéricos
        valores_unicos_str = valores_unicos.astype(str)
        
        # Verificar si la columna tiene exactamente dos valores únicos y si son numéricos

data_analysis/templates/data_analysis/arbol_decision_clasificacion.html
{% extends "data_analysis/plantilla_analisis.html" %}

{% block title %}Árbol de Decisión de Clasificación{% endblock %}

{% block formulario %}

    <form action="{% url 'data_analysis:arbol_decision_clasificacion' file_name=file_name %}" method="post">
            {% csrf_token %}
            <div class="d-flex align-items-center mb-4 justify-content-between">
                <h5 class="mb-0 me-4">Árbol de Decisión de Clasificación</h5>
                <!-- Botón para abrir el modal, ajustado para estar al lado del h5 -->
                <button type="button" class="btn btn-outline-info p-1" data-bs-toggle="modal" data-bs-target="#modalInstrucciones">
                    <i class="bi bi-book"></i> Ayuda
                </button>
            </div>

            <div class="d-flex gap-4 justify-content-start flex-wrap mt-2 mb-4">
                
                <div>
                    <p>Selecciona la variable objetivo (Y)</p>
                    <select class="form-select" id="variable_objetivo" name="variable_objetivo">
                        {% for columna in columnas_categoricas %}
                        {% if columna|length > 0 %}
                        <option value="{{ columna }}">{{ columna }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
                
                <div style="width: 100%">
                    <p>Selecciona las características (X)</p>
                    <div class="form-check mb-2">
                        <!-- Casilla para seleccionar o deseleccionar todo -->
                        <input class="form-check-input" type="checkbox" id="seleccionar_todo">
                        <label class="form-check-label mb-2" for="seleccionar_todo" style="font-weight: bold;">
                            Seleccionar todo
                        </label>
                    </div>
                    <!-- Distribución de columnas utilizando el sistema de grid de Bootstrap -->
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-6 g-0">
                        {% for columna in columnas_numericas %}
                        <div class="col" style="overflow: hidden">
                            <div class="form-check mb-2">
                                <input class="form-check-input" type="checkbox" name="caracteristicas" value="{{ columna }}" id="check_{{ columna }}">
                                <label class="form-check-label text-truncate" for="check_{{ columna }}" title="{{ columna }}" style="max-width: 90%; cursor: pointer;">
                                    {{ columna }}
                                </label>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="max_depth">Profundidad máxima:</label>
                    <input type="number" class="form-control" id="max_depth" name="max_depth" min="1" value="3">
                </div>

                <div class="form-group">
                    <label for="min_samples_leaf">Mínimo de muestras por hoja:</label>
                    <input type="number" class="form-control" id="min_samples_leaf" name="min_samples_leaf" min="1" value="1">
                </div>

            </div>

            {{ block.super }}
    </form>

    <!-- seleccionar todo -->
    <script>
        document.getElementById('seleccionar_todo').addEventListener('change', function() {
            var checkboxes = document.querySelectorAll('[name="caracteristicas"]');
            checkboxes.forEach(chk => {
                chk.checked = this.checked;
            });
        });
    </script>

    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip();
            // Cerrar el modal al presionar el botón de cerrar o hacer clic fuera del modal
            $('#modalInstrucciones').on('hidden.bs.modal', function () {
            });
        });
    </script>

<!-- Modal de Instrucciones de Uso -->
<div class="modal fade" id="modalInstrucciones" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Instrucciones de uso</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>Árbol de Decisión de Clasificación</h5>
                <p>Un árbol de decisión de clasificación es una herramienta de aprendizaje automático utilizada para predecir una variable objetivo categórica (booleana) basada en varias características de entrada. Este modelo divide los datos en ramas que representan decisiones basadas en las características de los datos.</p>

                <hr>
                <h5>Pasos a Seguir</h5>
                <ol>
                    <li><strong>Selecciona la Variable Objetivo (Y):</strong> Elige la variable objetivo booleana que deseas predecir.</li>
                    <li><strong>Selecciona las Características (X):</strong> Elige las columnas o variables que deseas utilizar para predecir la variable objetivo. Puedes seleccionar todas las columnas.</li>
                    <li><strong>Profundidad Máxima:</strong> Define la profundidad máxima del árbol. Esto controla hasta qué punto se dividirá el árbol. Un valor mayor puede llevar a un ajuste excesivo, mientras que un valor menor puede llevar a un ajuste insuficiente.</li>
                    <li><strong>Mínimo de Muestras por Hoja:</strong> Define el número mínimo de muestras que debe tener una hoja final. Esto ayuda a evitar la división de hojas que contienen muy pocos datos.</li>
                </ol>

                <hr>
                <h6>Ejemplo</h6>
                <div class="text-center">
                    <pre>| Edad | Colesterol | Presión Arterial | Problema Cardiaco (Y) |
| --- | --- | --- | --- |
| 45  | 220       | 130              | Sí                   |
| 50  | 180       | 120              | No                   |
| 40  | 200       | 140              | Sí                   |
| 60  | 240       | 150              | Sí                   |
| 55  | 210       | 135              | No                   |
| 48  | 230       | 145              | Sí                   |
| 52  | 190       | 125              | No                   |
| 47  | 195       | 140              | No                   |
| 43  | 205       | 130              | Sí                   |
| 58  | 215       | 135              | Sí                   |</pre>
                </div>

                <hr>
                <h6>Variable Objetivo (Y): "Problema Cardiaco"</h6>
                <h6>Características (X): "Edad", "Colesterol", "Presión Arterial"</h6>

                <hr>
                <h6>Configuraciones del Árbol de Decisión</h6>
                <p><strong>Profundidad Máxima:</strong> 3</p>
                <p><strong>Mínimo de Muestras por Hoja:</strong> 2</p>

                <hr>
                <h6>Resultados del Árbol de Decisión</h6>
                <p>Al entrenar el modelo con estas configuraciones, se obtiene un árbol de decisión que puede predecir si un paciente tiene un problema cardiaco basado en su edad, nivel de colesterol y presión arterial. El árbol se construirá de manera que se tomen decisiones óptimas en cada nodo hasta alcanzar la profundidad máxima o el mínimo de muestras por hoja especificado.</p>
            </div>
        </div>
    </div>
</div>



            
{% endblock %}

data_analysis/templates/data_analysis/correlacion_pearson.html
{% extends "data_analysis/plantilla_analisis.html" %}

{% block title %}Correlación de Pearson{% endblock %}

{% block formulario %}

    <form action="{% url 'data_analysis:correlacion_pearson' file_name=file_name %}" method="post">
        {% csrf_token %}
        <div class="d-flex align-items-center mb-4 justify-content-between">
            <h5 class="mb-0 me-4">Correlación de Pearson</h5>
            <!-- Botón para abrir el modal -->
            <button type="button" class="btn btn-outline-info p-1" data-bs-toggle="modal" data-bs-target="#modalInstrucciones">
                <i class="bi bi-book"></i> Ayuda
            </button>
        </div>

        <div class="d-flex gap-4 justify-content-start flex-wrap mt-2 mb-4">
            
            <div style="width: 100%">
                <p>Selecciona las variables a analizar</p>
                <div class="form-check mb-2">
                    <!-- Casilla para seleccionar o deseleccionar todo -->
                    <input class="form-check-input" type="checkbox" id="seleccionar_todo">
                    <label class="form-check-label mb-2" for="seleccionar_todo" style="font-weight: bold;">
                        Seleccionar todo
                    </label>
                </div>
                <!-- Distribución de columnas utilizando el sistema de grid de Bootstrap -->
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-6 g-0">
                    {% for columna in columnas %}
                    <div class="col" style="overflow: hidden">
                        <div class="form-check mb-2">
                            <input class="form-check-input" type="checkbox" name="variables" value="{{ columna }}" id="check_{{ columna }}">
                            <label class="form-check-label text-truncate" for="check_{{ columna }}" title="{{ columna }}" style="max-width: 90%; cursor: pointer;">
                                {{ columna }}
                            </label>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            
        </div>

        {{ block.super }}
    </form>

    <!-- seleccionar todo -->
    <script>
        document.getElementById('seleccionar_todo').addEventListener('change', function() {
            var checkboxes = document.querySelectorAll('[name="variables"]');
            checkboxes.forEach(chk => {
                chk.checked = this.checked;
            });
        });
    </script>

    {% comment %} modal {% endcomment %}
    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip();
            // Cerrar el modal al presionar el botón de cerrar o hacer clic fuera del modal
            $('#modalInstrucciones').on('hidden.bs.modal', function () {
            });
        });
    </script>
    
<!-- Modal de Instrucciones de Uso -->
<div class="modal fade" id="modalInstrucciones" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Instrucciones de uso</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>Correlación de Pearson</h5>
                <p>La correlación de Pearson mide la fuerza y la dirección de la relación lineal entre dos variables numéricas. El coeficiente de correlación de Pearson varía entre -1 y 1, donde:</p>
                <ul>
                    <li>1 indica una correlación positiva perfecta.</li>
                    <li>-1 indica una correlación negativa perfecta.</li>
                    <li>0 indica que no hay correlación lineal.</li>
                </ul>

                <hr>
                <h5>Pasos a Seguir</h5>
                <ol>
                    <li><strong>Selecciona las Variables a Analizar:</strong> Elige las variables numéricas del dataset que deseas analizar para calcular la correlación de Pearson. Puedes seleccionar todas las columnas o elegir columnas específicas.</li>
                </ol>

                <hr>
                <h6>Ejemplo</h6>
                <p>Supongamos que se tiene el siguiente DataFrame con varias variables numéricas:</p>
                <div class="text-center">
                    <pre>| Edad | Colesterol | Presión Arterial | Ingresos |
| --- | --- | --- | --- |
| 45  | 220 | 140              | 50000    |
| 50  | 180 | 120              | 60000    |
| 40  | 200 | 130              | 55000    |
| 60  | 240 | 150              | 65000    |
| 55  | 210 | 140              | 70000    |</pre>
                </div>
                
                <hr>
                <h6>Resultados</h6>
                <p>Al seleccionar todas las variables, se calcularán los coeficientes de correlación de Pearson entre cada par de variables:</p>
                <div class="text-center">
                    <pre>|                 | Edad | Colesterol | Presión Arterial | Ingresos |
| ---             | ---  | ---        | ---              | ---      |
| Edad            | 1    | 0.8        | 0.6              | 0.9      |
| Colesterol      | 0.8  | 1          | 0.7              | 0.85     |
| Presión Arterial| 0.6  | 0.7        | 1                | 0.65     |
| Ingresos        | 0.9  | 0.85       | 0.65             | 1        |</pre>
                </div>
                <p>Estos valores indican la fuerza y la dirección de las relaciones lineales entre las variables seleccionadas.</p>
            </div>
        </div>
    </div>
</div>


{% endblock %}

data_analysis/templates/data_analysis/plantilla_analisis.html
{% extends "layouts/base.html" %}

{% block title %}Análisis{% endblock %}

{% block content %}
<div class="d-flex flex-column gap-2">
    <div class="bg-white rounded shadow p-4 mt-4 flex-shrink-1">
        {% block formulario %}
            <form method="post">
                {% csrf_token %}
                
                {% if error_message %}
                <div class="alert alert-danger mb-4" role="alert">
                    {{ error_message }}
                </div>
                {% endif %}

                <div>
                    <button type="submit" class="btn btn-primary">Analizar</button>
                </div>
            </form>
        {% endblock %}	
    </div>

    <div class="flex-fill">
        {% include "file_handler/_scrollable_table.html" %}
    </div>

</div>
{% endblock %}