Sistema_analisis_estadistico/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
import os


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('file_handler.urls')),
    path('data_cleaning/', include('data_cleaning.urls')),
    path('data_transformation/', include('data_transformation.urls')),
    path('data_analysis/', include ('data_analysis.urls')),
    path('report/', include('report.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static('/temp_files/', document_root=os.path.join(settings.BASE_DIR, 'temp_files'))

data_cleaning/urls.py
from . import views
from django.urls import path


app_name = 'data_cleaning'

urlpatterns = [
    path('opciones_limpieza_hub/<str:file_name>/', views.opciones_limpieza_hub, name='opciones_limpieza'),
    path('eliminar_columnas/<str:file_name>/', views.eliminar_columnas, name='eliminar_columnas'),
    path('normalizar_texto/<str:file_name>', views.normalizar_texto, name='normalizar_texto'),
    path('manejar_valores_vacios/<str:file_name>', views.manejar_valores_vacios, name='manejar_valores_vacios'),
    path('procesar_outliers/<str:file_name>', views.procesar_outliers, name='procesar_outliers'),
    path('filtrar:datos/<str:file_name>', views.filtrar_datos, name='filtrar_datos'),
]

report/urls.py
from . import views
from django.urls import path

app_name = 'report'

urlpatterns = [
    path('exportar_reporte/', views.exportar_reporte, name='exportar_reporte'),

    path('reporte_distribucion_frecuencias/<str:file_name>', views.reporte_distribucion_frecuencias, name='reporte_distribucion_frecuencias'),
    path('reporte_tendencia_central/<str:file_name>', views.reporte_tendencia_central, name='reporte_tendencia_central'),
    path('reporte_variabilidad/<str:file_name>', views.reporte_variabilidad, name='reporte_variabilidad'),    


    path('reporte_regresion_linear/<str:file_name>', views.reporte_regresion_linear, name='reporte_regresion_linear'),
    path('reporte_regresion_logistica/<str:file_name>', views.reporte_regresion_logistica, name='reporte_regresion_logistica'),  
    path('reporte_correlacion_pearson/<str:file_name>', views.reporte_correlacion_pearson, name='reporte_correlacion_pearson'),
    path('reporte_correlacion_spearman/<str:file_name>', views.reporte_correlacion_spearman, name='reporte_correlacion_spearman'),  
    path('reporte_kmeans_clustering/<str:file_name>', views.reporte_kmeans_clustering, name='reporte_kmeans_clustering'),  
    path('reporte_arbol_decision_clasificacion/<str:file_name>', views.reporte_arbol_decision_clasificacion, name='reporte_arbol_decision_clasificacion'),


    path('reporte_intervalo_confianza/<str:file_name>', views.reporte_intervalo_confianza, name='reporte_intervalo_confianza'),  
    path('reporte_prueba_hipotesis/<str:file_name>', views.reporte_prueba_hipotesis, name='reporte_prueba_hipotesis'),
    path('reporte_perceptron/<str:file_name>', views.reporte_perceptron, name='reporte_perceptron'),    

]

data_cleaning/models.py
from django.db import models

# Create your models here.

data_cleaning/views.py
from http.client import HTTPResponse
from django.shortcuts import redirect, render
from .utils import cleaning_utils
from .utils.views_utils import guardar_resultado_en_sesion, preparar_datos_para_get
from utils.csv_utils import gestionar_version_archivo, leer_csv_o_error, guardar_csv
from utils.tablas_utils import crear_inicio_tabla

# Vistas dedicadas a la limpieza de datos
# Se encargan de manejar las opciones de limpieza de datos y de procesar los datos según las opciones seleccionadas
# También se encarga de guardar los resultados en la sesión y de redirigir a la vista de revisión de CSV
# Se incluyen las vistas: opciones_limpieza_hub, eliminar_columnas, normalizar_texto, manejar_valores_vacios, procesar_outliers y filtrar_datos

def opciones_limpieza_hub(request, file_name):
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo') # necesita cambiarse. Muy primitivo.
    
    df_html = crear_inicio_tabla(df)
    info = request.session.get('info', None) # Obtiene el mensaje de éxito o error
    request.session['info'] = None  # Borra el mensaje de la sesión

    return render(request, 'data_cleaning/opciones_limpieza.html', {
        'file_name': file_name,
        'dataframe': df_html,
        'info': info
    })

def eliminar_columnas(request, file_name):
    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')
    
    # Preparación para el método GET
    df_html, columnas = preparar_datos_para_get(df)

    # Manejo de POST
    if request.method == 'POST':
        columnas_a_manipular = request.POST.getlist('columnas_a_manipular')

        if not columnas_a_manipular:
            error_message = "Debe seleccionar al menos una columna."
            return render(request, 'data_cleaning/limpieza_columnas.html', {
                'file_name': file_name,
                'dataframe': df_html,
                'columnas': columnas,
                'error_message': error_message
            })

        new_file_name, new_file_path = gestionar_version_archivo(request, file_name)
        
        df_procesado, resultado = cleaning_utils.eliminar_columnas(df, columnas_a_manipular)
        
        guardar_resultado_en_sesion(request, resultado)
        guardar_csv(df_procesado, new_file_path)
        return redirect('file_handler:revisar_csv', file_name=new_file_name)


    return render(request, 'data_cleaning/limpieza_columnas.html', {
        'file_name': file_name,
        'columnas': columnas,
        'dataframe': df_html
    })


def normalizar_texto(request, file_name):
    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')

    # Preparación para el método GET
    df_html, columnas = preparar_datos_para_get(df, include_dtypes=['object'])

    # Manejo de POST
    if request.method == 'POST':
        alcance = request.POST.get('alcance', '')
        columnas_a_manipular = request.POST.getlist('columnas_a_manipular')

        if alcance == 'columna_especifica' and not columnas_a_manipular :
            error_message = "Debe seleccionar al menos una columna."
            return render(request, 'data_cleaning/normalizar_texto.html', {
                'file_name': file_name,
                'dataframe': df_html,
                'columnas': columnas,
                'error_message': error_message
            })

        new_file_name, new_file_path = gestionar_version_archivo(request, file_name)
        df_procesado, resultado = cleaning_utils.normalizar_texto(df, alcance, columnas_a_manipular)

        guardar_resultado_en_sesion(request, resultado)
        guardar_csv(df_procesado, new_file_path)
        return redirect('file_handler:revisar_csv', file_name=new_file_name)


    return render(request, 'data_cleaning/normalizar_texto.html', {
        'file_name': file_name,
        'columnas': columnas, 
        'dataframe': df_html
    })

def manejar_valores_vacios(request, file_name):
    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')


    # Preparación para el método GET
    df_html, columnas = preparar_datos_para_get(df)


    # Manejo de POST
    if request.method == 'POST':
        alcance = request.POST.get('alcance', '')
        accion = request.POST.get('accion', '')
        columnas_a_manipular = request.POST.getlist('columnas_a_manipular')

        if alcance == 'columna_especifica' and not columnas_a_manipular :
            error_message = "Debe seleccionar al menos una columna."
            return render(request, 'data_cleaning/manejar_valores_vacios.html', {
                'file_name': file_name,
                'dataframe': df_html,
                'columnas': columnas,
                'error_message': error_message
            })

        new_file_name, new_file_path = gestionar_version_archivo(request, file_name)
        df_procesado, resultado = cleaning_utils.manejar_valores_vacios(df, alcance, columnas_a_manipular, accion)

        guardar_resultado_en_sesion(request, resultado)
        guardar_csv(df_procesado, new_file_path)
        return redirect('file_handler:revisar_csv', file_name=new_file_name)

    return render(request, 'data_cleaning/manejar_valores_vacios.html', {
        'file_name': file_name,
        'columnas': columnas,
        'dataframe': df_html
    })

def procesar_outliers(request, file_name):
    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')

    # Preparación para el método GET
    df_html, columnas = preparar_datos_para_get(df, include_dtypes=['number'])


    # Manejo de POST
    if request.method == 'POST':
        accion = request.POST.get('accion', '')
        umbral_iqr = float(request.POST.get('umbral_iqr', 1.5))
        columnas_a_manipular = request.POST.getlist('columnas_a_manipular')

        if not columnas_a_manipular :
            error_message = "Debe seleccionar al menos una columna."
            return render(request, 'data_cleaning/manejar_valores_vacios.html', {
                'file_name': file_name,
                'dataframe': df_html,
                'columnas': columnas,
                'error_message': error_message
            })

        new_file_name, new_file_path = gestionar_version_archivo(request, file_name)
        df_procesado, resultado = cleaning_utils.procesar_outliers_iqr(df, columnas_a_manipular=columnas_a_manipular, umbral_iqr=umbral_iqr, accion=accion)

        guardar_resultado_en_sesion(request, resultado)
        guardar_csv(df_procesado, new_file_path)
        return redirect('file_handler:revisar_csv', file_name=new_file_name)


    return render(request, 'data_cleaning/procesar_outliers.html', {
        'file_name': file_name,
        'columnas': columnas,
        'dataframe': df_html
    })

def filtrar_datos(request, file_name):
    # Manejo de error y carga de DataFrame
    df, error_response, file_path = leer_csv_o_error(request, file_name)
    if error_response:
        return redirect('file_handler:cargar_archivo')

    # Preparación para el método GET
    df_html, columnas = preparar_datos_para_get(df, include_dtypes=['number'])

    # Manejo de POST
    if request.method == 'POST':
        columnas_a_manipular = request.POST.getlist('columnas_a_manipular')
        condicion_str = request.POST.get('condicion', '')

        if not columnas_a_manipular or not condicion_str :
            error_message = "Debe seleccionar al menos una columna y definir una condición."
            return render(request, 'data_cleaning/filtrar_datos.html', {
                'file_name': file_name,
                'dataframe': df_html,
                'columnas': columnas,
                'error_message': error_message
             })

        new_file_name, new_file_path = gestionar_version_archivo(request, file_name)
        df_procesado, resultado = cleaning_utils.filtrar_filas_por_condicion(df, columnas_a_manipular, condicion_str)

        guardar_resultado_en_sesion(request, resultado)
        guardar_csv(df_procesado, new_file_path)
        return redirect('file_handler:revisar_csv', file_name=new_file_name)

    return render(request, 'data_cleaning/filtrar_datos.html', { 
        'file_name': file_name,
        'columnas': columnas,
        'dataframe': df_html
    })

data_cleaning/templates/data_cleaning/filtrar_datos.html
{% extends "data_cleaning/plantilla_opciones.html" %}
{% block title %}Filtrar datos{% endblock %}

{% block formulario %}
    <form action="{% url 'data_cleaning:filtrar_datos' file_name=file_name %}" method="post"> 
        {% csrf_token %}
        <div class="d-flex align-items-center mb-4 justify-content-between">
            <h5 class="mb-0 me-4">Filtrar datos por condición</h5>
            <!-- Botón para abrir el modal -->
            <button type="button" class="btn btn-outline-info p-1" data-bs-toggle="modal" data-bs-target="#modalInstrucciones">
                <i class="bi bi-book"></i> Ayuda
            </button>
        </div>
        
        
        <div class="d-flex gap-4 justify-content-start flex-wrap mt-2 mb-4">
            <div>
                <p>Defina la condición de filtrado:</p>
                <div>
                    <input type="text" class="form-control" id="condicion" name="condicion" placeholder="Ej: x > 0">
                    <small class="form-text text-muted">Ingrese una expresión válida. Ejemplo: x > 0 para conservar valores mayores a 0.</small>
                    <small class="form-text text-muted">Las filas que no pasen el filtro serán eliminadas.</small>
                </div>
            </div>

            <div style="width: 100%">
                <p>Seleccione las columnas que desea evaluar:</p>
                <div class="form-check mb-2">
                    <!-- Casilla para seleccionar o deseleccionar todo -->
                    <input class="form-check-input" type="checkbox" id="seleccionar_todo">
                    <label class="form-check-label mb-2" for="seleccionar_todo" style="font-weight: bold;">
                        Seleccionar todo
                    </label>
                </div>
                <!-- Distribución de columnas -->
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-6 g-0">
                    {% for columna in columnas %}
                    <div class="col" style="overflow: hidden">
                        <div class="form-check mb-2">
                            <input class="form-check-input" type="checkbox" name="columnas_a_manipular" value="{{ columna }}" id="check_{{ columna }}">
                            <label class="form-check-label text-truncate" for="check_{{ columna }}" title="{{ columna }}" style="max-width: 90%; cursor: pointer;">
                                {{ columna }}
                            </label>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if not columnas %}
                    <small class="text-info">
                        <i class="bi bi-info-circle-fill"></i> No hay columnas disponibles para evaluar.
                    </small>
                {% endif %}
            </div>
            
        </div>

        {{ block.super }}
    </form>

        <!-- seleccionar todo -->
    <script>
        document.getElementById('seleccionar_todo').addEventListener('change', function() {
            var checkboxes = document.querySelectorAll('[name="columnas_a_manipular"]');
            checkboxes.forEach(chk => {
                chk.checked = this.checked;
            });
        });
    </script>

    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip();
            // Cerrar el modal al presionar el botón de cerrar o hacer clic fuera del modal
            $('#modalInstrucciones').on('hidden.bs.modal', function () {
            });
        });
    </script>


    <!-- Modal de Instrucciones de Uso -->
<div class="modal fade" id="modalInstrucciones" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Instrucciones de uso</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>Filtrar datos por Condición</h5>
                <p>La filtración de datos por condición implica seleccionar solo las filas que cumplen con una condición específica, descartando las que no la cumplen.</p>

                <hr>
                <h5>Pasos a Seguir</h5>
                <ol>
                    <li><strong>Definir la Condición de Filtrado:</strong> Especifica la condición que deben cumplir los datos para ser incluidos en el análisis. Debe ser una comparación numérica.</li>
                    <li><strong>Seleccionar las Columnas a Evaluar:</strong> Decide qué columnas numéricas del dataset deseas evaluar para aplicar la condición de filtrado. Puedes seleccionar todas las columnas o elegir columnas específicas.</li>
                    <li><strong>Aplicar la Condición de Filtrado:</strong> Filtra las filas del dataset que cumplen con la condición especificada. Las filas que no cumplan con la condición serán eliminadas del dataset resultante.</li>
                </ol>

                <hr>
                <h6>Ejemplo</h6>
                <p>Supongamos que se tiene el siguiente DataFrame con valores numéricos:</p>
                <div class="text-center">
                    <pre>| Valor | Categoría |
| --- | --- |
| 10 | A |
| -5 | B |
| 8 | A |
| 15 | C |
| 7 | B |
| 20 | A |
| 25 | C |</pre>
                </div>

                <hr>
                <h6>Resultados</h6>
                <p>Se eliminan las filas que no cumplen con la condición especificada:</p>
                <div class="text-center">
                    <pre>| Valor | Categoría |
| --- | --- |
| 10 | A |
| 8 | A |
| 15 | C |
| 20 | A |
| 25 | C |</pre>
                </div>
                <p>En este ejemplo, las filas con valores negativos (como -5 y 7) son eliminadas, ya que no cumplen con la condición de ser mayores que 0.</p>
            </div>
        </div>
    </div>
</div>

    
{% endblock %}

data_cleaning/templates/data_cleaning/limpieza_columnas.html
{% extends "data_cleaning/plantilla_opciones.html" %}
{% block title %}Eliminar columnas{% endblock %}

{% block formulario %}

<form action="{% url 'data_cleaning:eliminar_columnas' file_name=file_name %}" method="post">
    {% csrf_token %}
    <div class="d-flex align-items-center mb-4 justify-content-between">
        <h5 class="mb-0 me-4">Eliminar columnas</h5>
        <!-- Botón para abrir el modal -->
        <button type="button" class="btn btn-outline-info p-1" data-bs-toggle="modal" data-bs-target="#modalInstrucciones">
            <i class="bi bi-book"></i> Ayuda
        </button>
    </div>

    <div class="d-flex gap-4 justify-content-start flex-wrap mt-2 mb-4">
        <div style="min-width: 60%">
            <p>Seleccione las columnas que desea eliminar:</p>
            <div class="form-check mb-2">
                <!-- Casilla para seleccionar o deseleccionar todo -->
                <input class="form-check-input" type="checkbox" id="seleccionar_todo">
                <label class="form-check-label mb-2" for="seleccionar_todo" style="font-weight: bold;">
                    Seleccionar todo
                </label>
            </div>
            <!-- Distribución de columnas -->
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-6 g-0">
                {% for columna in columnas %}
                <div class="col" style="overflow: hidden">
                    <div class="form-check mb-2">
                        <input class="form-check-input" type="checkbox" name="columnas_a_manipular" value="{{ columna }}" id="check_{{ columna }}">
                        <label class="form-check-label text-truncate" for="check_{{ columna }}" title="{{ columna }}" style="max-width: 90%; cursor: pointer;">
                            {{ columna }}
                        </label>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {{ block.super }}
</form>

<!-- seleccionar todo -->
<script>
    document.getElementById('seleccionar_todo').addEventListener('change', function() {
        var checkboxes = document.querySelectorAll('[name="columnas_a_manipular"]');
        checkboxes.forEach(chk => {
            chk.checked = this.checked;
        });
    });
</script>


<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
        // Cerrar el modal al presionar el botón de cerrar o hacer clic fuera del modal
        $('#modalInstrucciones').on('hidden.bs.modal', function () {
        });
    });
</script>


<!-- Modal de Instrucciones de Uso -->
<div class="modal fade" id="modalInstrucciones" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Instrucciones de uso</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>Eliminar Columnas</h5>
                <p>La función de eliminar columnas permite al usuario seleccionar una o más columnas del DataFrame y, al aplicar los cambios, estas columnas serán eliminadas del DataFrame.</p>

                <hr>
                <h5>Pasos a Seguir</h5>
                <ol>
                    <li><strong>Seleccionar Columnas:</strong> Decide qué columnas del DataFrame deseas eliminar. Puedes seleccionar una o varias columnas.</li>
                    <li><strong>Aplicar Cambios:</strong> Una vez seleccionadas las columnas a eliminar, aplica los cambios para que estas columnas sean removidas del DataFrame.</li>
                </ol>

                <hr>
                <h6>Ejemplo</h6>
                <p>Supongamos que se tiene el siguiente DataFrame:</p>
                <div class="text-center">
                    <pre>| Nombre  | Edad | Ciudad    | Ocupación |
| ------- | ---- | --------- | ---------- |
| Juan    | 28   | Madrid    | Ingeniero  |
| María   | 34   | Barcelona | Doctora    |
| Pedro   | 45   | Valencia  | Profesor   |
| Ana     | 29   | Sevilla   | Abogada    |</pre>
                </div>

                <hr>
                <h6>Resultados</h6>
                <p>Si se eliminan las columnas "Edad" y "Ciudad", el DataFrame resultante será:</p>
                <div class="text-center">
                    <pre>| Nombre  | Ocupación |
| ------- | ---------- |
| Juan    | Ingeniero  |
| María   | Doctora    |
| Pedro   | Profesor   |
| Ana     | Abogada    |</pre>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

data_cleaning/templates/data_cleaning/manejar_valores_vacios.html
{% extends "data_cleaning/plantilla_opciones.html" %}

{% block formulario %}

<form action="{% url 'data_cleaning:manejar_valores_vacios' file_name=file_name %}" method="post">
    {% csrf_token %}
    <div class="d-flex align-items-center mb-4 justify-content-between">
        <h5 class="mb-0 me-4">Manejar valores vacíos</h5>
        <button type="button" class="btn btn-outline-info p-1" data-bs-toggle="modal" data-bs-target="#modalValoresVacios">
            <i class="bi bi-book"></i> Ayuda
        </button>
    </div>

    <div class="d-flex gap-4 justify-content-start flex-wrap mt-2 mb-4">
        <div>
            <p>Seleccione el Alcance:</p>
            <select class="form-select" id="alcance" name="alcance">
                <option value="todo">Todo el dataset</option>
                <option value="columna_especifica">Elegir columnas</option>
            </select>
        </div>

        <div>
            <p>Acción para los valores vacíos:</p>
            <select class="form-select" id="accion" name="accion">
                <option value="eliminar">Eliminar Filas con Valores Vacíos</option>
                <option value="cero_no_definido">Reemplazar con 0 / 'No definido'</option>
                <option value="media_mas_comun">Reemplazar con la Media / Valor Más Común</option>
            </select>
        </div>
    
        <div id="group_columna_especifica" style="display: none; width: 100%">
            <p>Seleccione las columnas a manejar:</p>
            <div class="form-check mb-2">
                <input class="form-check-input" type="checkbox" id="seleccionar_todo">
                <label class="form-check-label mb-2" for="seleccionar_todo" style="font-weight: bold;">
                    Seleccionar todo
                </label>
            </div>
            <!-- Distribución de columnas -->
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-6 g-0">
                {% for columna in columnas %}
                <div class="col" style="overflow: hidden">
                    <div class="form-check mb-2">
                        <input class="form-check-input" type="checkbox" name="columnas_a_manipular" value="{{ columna }}" id="check_{{ columna }}">
                        <label class="form-check-label text-truncate" for="check_{{ columna }}" title="{{ columna }}" style="max-width: 90%; cursor: pointer;">
                            {{ columna }}
                        </label>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    
    </div>

    {{ block.super }}
</form>

<script>
    document.getElementById('alcance').addEventListener('change', function() {
        var group = document.getElementById('group_columna_especifica');
        group.style.display = (this.value === 'columna_especifica') ? 'block' : 'none';
    });
</script>
<script>
    document.getElementById('seleccionar_todo').addEventListener('change', function() {
        var checkboxes = document.querySelectorAll('[name="columnas_a_manipular"]');
        checkboxes.forEach(chk => {
            chk.checked = this.checked;
        });
    });
</script>

<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
        $('#modalValoresVacios').on('hidden.bs.modal', function () {
        });
    });
</script>


<div class="modal fade" id="modalValoresVacios" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Instrucciones de uso</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5>Manejar Valores Vacíos</h5>
                <p>Manejar valores vacíos es crucial para asegurar la calidad y la integridad de los datos. Las columnas donde se encuentren valores vacíos se pueden reemplazar por (0 / ‘No definido’), siendo cero en caso de las numéricas o ‘No definido’ en caso de categóricas, o reemplazar por la (Medía/Valor más común).</p>

                <hr>
                <h5>Pasos a Seguir</h5>
                <ol>
                    <li><strong>Seleccione el Alcance:</strong> Decide si deseas aplicar la acción a todo el dataset o solo a columnas específicas.</li>
                    <li><strong>Aplicar la Acción para los Valores Vacíos:</strong>
                        <ul>
                            <li>Elige entre reemplazar con un valor específico o con (0 / ‘No definido’).</li>
                            <li>Elige entre reemplazar con un valor específico o con la (Medía/Valor más común).</li>
                        </ul>
                    </li>
                </ol>

                <hr>
                <h6>Ejemplo</h6>
                <p>Supongamos que tienes el siguiente DataFrame con algunos valores vacíos:</p>
                <div class="text-center">
                    <pre>| Nombre     | Edad | Ciudad     |
|------------|------|------------|
| John Doe   | 28   | Nueva York |
| Jane Smith |      | Los Ángeles|
| Alice      | 34   |            |
| Bob        |      | Nueva York |
</pre>
                </div>

                <hr>
                <h6>Resultados</h6>
                <h6>Reemplazar con (0/'No definido'):</h6>
                <div class="text-center">
                    <pre>| Nombre     | Edad | Ciudad       |
|------------|------|--------------|
| John Doe   | 28   | Nueva York   |
| Jane Smith | 0    | Los Ángeles  |
| Alice      | 34   | 'No definido'|
| Bob        | 0    | Nueva York   |
</pre>
                </div>

                <hr>
                <h6>Reemplazar con la Media/Valor Más Común:</h6>
                <p>La media en la columna edad sería 30.67.</p>
                <p>El valor más común en la columna ciudad sería ‘Nueva York’.</p>
                <div class="text-center">
                    <pre>| Nombre     | Edad | Ciudad     |
|------------|------|------------|
| John Doe   | 28   | Nueva York |
| Jane Smith | 30.67| Los Ángeles|
| Alice      | 34   | Nueva York |
| Bob        | 30.67| Nueva York |
</pre>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

data_cleaning/templates/data_cleaning/plantilla_opciones.html
{% extends "layouts/base.html" %}

{% block title %}Limpieza{% endblock %}

{% block content %}
<div class="d-flex flex-column gap-2">
    <div class="bg-white rounded shadow p-4 mt-4 flex-shrink-1">
        {% block formulario%}

        {% if error_message %}
        <div class="alert alert-danger mb-4" role="alert">
            {{ error_message }}
        </div>
        {% endif %}
        
        <div>
            <button type="submit" class="btn btn-primary">Aplicar Limpieza</button>
        </div>
        

        {% endblock %}	
    </div>

    <div class="flex-fill">
        {% include "file_handler/_scrollable_table.html" %}
    </div>

</div>
{% endblock %}